language: java
jdk:
- openjdk7
script:
- ./build-travis.sh
- ./bundle.sh $TRAVIS_BUILD_NUMBER
- ./publish-mvn.sh $TRAVIS_BUILD_NUMBER
sudo: false
deploy:
  provider: s3
  access_key_id: AKIAJGDNLDUHILTARBTA
  secret_access_key:
    secure: esYEUi03l6XNFYDP+tZ0pE0SNSvb5rMmnmKeytL/UnYX72aWhyxNaOohDwr+LxgxcfJDSI9AEjjpl6iyHwLMwSYnUL4+SSRtUnbIlQlF4seMDOEstpHwjX01Myzltd8907pjM7kBwNTOO+eWme/5OxBy8JOwlJaL1vV06/xvl+U=
  bucket: omny-cms-releases
  skip_cleanup: true
  local-dir: output
  on:
    repo: omnycms/omny-cms
    branch: master
    
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Hm2rURHfTnFw02CVUL41Rv0md7LzEq+Zv0Pz3ULJpwDcUtc/dMOfparRJxzQVQpGSpT48Cd8XWZz2zAB27C817ylVXYSncpmkAiVHFNdb62thss/j11jwW83h2lUQQjb72LIKphnc86EMQR5hPyWUnG/fCW5rn7cNJYTfy0BFWA="

addons:
  coverity_scan:
    project:
      name: "omnycms/omny-cms"
      description: "Omny microservice CMS"
    notification_email: alamarre@gmail.com
    build_command:   "./build-travis.sh"
    branch_pattern: master
